using System.Collections.Generic;
using System.Text;
using Microsoft.SemanticKernel;

namespace Part1_Build_Restuarant_Agent;

public class KnowledgePlugin
{
    [KernelFunction("get_restaurant_menu")]
    public string GetRestaurantMenu()
    {
    return  """ 
            Dinner Menu-  Appetizers
            Okra FriesHand-cut, unbreaded fried okra, freshly squeezed lime juice, kosher salt, house-made ketchup10Fried Green Tomato "BLT"Pork belly, pimiento cheese, frisée, tomato jam16Gator TailChili-marinated Fresh From Florida alligator, dusted in seasoned flour, flash-fried, with spicy remoulade18Aji Amarillo CevicheLeche de tigre with Peruvian yellow pepper, mahi-mahi, shrimp, cala-mari, red onions, cilantro, choclo corn, serrano pepper, trout roe20Soft Shell CrabChesapeake Bay soft shell whole crab dusted in seasoned flour and flash fried, berbere seasoning, apple cider slaw, roasted garlic datil aioli22CalamariCrispy fried North Atlantic calamari, amarillo chili lemon dressing, sauce piquant18
    McKay Crab CakesNamed for Tampa pioneer and mariner James McKay, fresh Chesa-peak Bay lump blue crab, pan-seared, with sun-dried tomato herb bisque, frisée and scallion salad, Florida citrus dressing25Barbacoa ShrimpBlackened jumbo shrimp, parsnip and celery root purée, roasted tomato, charred asparagus tips, broken lemon vinaigrette18Tuna BenneBenne seed seared yellowfin tuna, wakame seaweed slaw, chadon sauce, white garlic wasabi cream and corn salsa18Mac & CheeseHydration Station Lager and smoked gouda sauce, three-cheese panko crust, cavatappi pasta8Add fresh blue crab meatAdd short rib1012ChiliNative ChiliAlligator, wild boar, venison, duck, ground chuck, cranberry beans and chili spices8 oz. bowl9Native Loaded ChiliLoaded with toppings of fresh jalapeño, red onion and white cheddar8 oz. bowl10
    SaladsMixed greens with baby Swiss, cranberry beans, fire-roasted pep-pers, onions, balsamic vinaigrette12Side salad with entreeAdd chicken or shrimp88Shaved Brussels SproutsDried cranberries, toasted almonds, Granny Smith apples and goat cheese with Florida citrus vinaigrette12Water Works WedgeIceberg lettuce, sliced grape tomatoes, country ham, diced red onion, goat cheese crumbles, green onions, fire-roasted corn salsa with red wine buttermilk dressing12Oysters From Our Gulf CoastOysters have been a local staple since the Tocobaga harvested them from these waters. We're pleased to serve delicious oysters from the Gulf Coast.Oysters Half ShellHalf dozenBaker's dozen2244Charbroiled OystersBarbacoa-grilled, garlic butter, grated Parmesan and Romano cheeses.Half dozenDozen2548
    Entrées - WaterWhen available, we serve fresh fish and seafood from our Gulf and coastal waters.Gouda GrouperGulf grouper fillet, smoked Gouda ale béchamel with wild rice blend and seasonal vegetable35Florida Pompano "Pallardy"Pan-seared fresh pompano, sun-dried tomato cream sauce and crawfish tail meat, wild rice blend, crisp carrot ribbons, seasonal vegetable32Mahi-Mahi "Mr. Henry"Blackened fillet of mahi-mahi with green papaya slaw, charred corn salsa, garlic spinach30Seafood RisottoPan-seared shrimp and sea scallops, butter-poached lobster claw, crawfish tail meat, saffron risotto, charred corn cream sauce and seasonal vegetable38Steelhead TroutPan-seared trout, datil pepper glaze, sweet potato purée, brown butter and balsamic crispy Brussels sprouts, herb oil35Tocobaga TunaSeared sliced yellowfin tuna, mixed greens, fire-roasted red pepper, kalamata olives, red onions, grape tomatoes, balsamic vinaigrette20Entrées - LandFire-Roasted Chicken25
    Grilled and seasoned boneless chicken breast, saffron risotto, garlic spinach, vine-ripened tomato garlic lemon basil sauceCrackling Pork Shank 1 Ib.Crispy Compart Family Duroc pork shank, firecracker apple-cran-berry-raisin chutney with roasted garlic mashed potatoes, seasonal vegetable30Barry's Tomahawk Pork Chop 14 oz.Compart Family Duroc bone-in pork chop, guava demi-glace, roasted garlic mashed potatoes, seasonal vegetable. Named in honor of legendary FSU Hall of Fame receiver #22 Barry Smith.36Water Works MeatloafGround strip loin, Cabernet garlic demi-glace, roasted garlic mashed potatoes, seasonal vegetable. Featured as "Best Thing I Ever Ate" by Food Network celebrity Chef Robert Irvine.26Braised Short RibRoot vegetable and Nitro Stout braised boneless short rib, roasted garlic mashed potatoes, root vegetable demi-glace and seasonal vegetable36Chef's Steak 8 oz.Hanger steak aged minimum of 21 days, with avocado "Jimmychurri," roasted fingerling potatoes and seasonal vegetable32Filet Mignon 8 oz.Aged minimum of 21 days, with roasted garlic mashed potatoes and seasonal vegetable46New York Strip 16 oz.Aged minimum of 21 days, with roasted garlic mashed potatoes and seasonal vegetable46
    Bone-in Ribeye 20 oz.Aged minimum of 21 days, with roasted garlic mashed potatoes and seasonal vegetable48Plant-BasedNative SautéA mix of freshly sautéed portobello mushrooms, red onions, zucchini, squash, green beans, white wine, sauce vierge, wild rice blend20Three Sisters Stuffed PortobelloOven-roasted marinated portobello cap stuffed with fresh grilled zucchini, squash, corn, red onion, red pepper, sautéed spinach, cran-berry beans, manchego cheese, wild rice blend, crisp carrot ribbons20SidesKarson's Jalapeño Corn Beer MuffinsRoasted fresh corn, pickled jalapeño, Pale Lager and creamed corn — baked daily and served with whipped butter8Carrot RibbonsCrisp carrot ribbons, dusted in flour then fried, with honey datil aioli6"Fuego" Street CornFire-roasted corn on the cob, seasoned and buttered6Desserts
    Pineapple Upside-Down Bread PuddingHouse-made toasted coconut ice cream, dark rum sauce12Bourbon Butter CakeWith house-made Ugandan vanilla bean ice cream, whipped cream, blackberry12Flourless Chocolate TorteRaspberry port wine reduction, whipped cream, shaved white choco-late10Key West Key Lime StackBrûléed meringue, key lime sauce10Candied Bacon Maple Ice CreamCorn flake crust, Knob Creek créme anglaise, caramel, waffle crisp11Coconut Ice CreamLightly toasted coconut ice cream, served in a coconut shell10Gustavo's Ice CreamTwo scoops. Vegetarian, gluten freeValrhona ChocolateA rich, decadent chocolate ice cream made with one of the best chocolates in the world8
    Ugandan Vanilla BeanA true classic – vanilla bean ice cream made with Ugandan Gold vanilla beans8Naviera Espresso Chocolate SwirlThis coffee ice cream is made with our signature blend of Tam-pa-roasted Naviera Espresso and a swirl of melted chocolate8Gustavo's Ice CreamFrom the 1940s to the 1960s, the Columbia Restaurant served ice cream from the Tropical Ice Cream Company, operated by Gustavo Hernandez, the third son of the Columbia's founder Casimiro Her-nandez, Sr.At this restaurant, we're again making our own ice cream, here on site, using only the freshest ingredients.Consuming raw or undercooked meats, poultry, seafood, shellfish, or eggs may increase your risk of foodborne illness, especially if you have certain medical conditions.Checkle for Business
    """;
    }
}
